# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import img.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=img.models._create_hash, max_length=100, unique=True)),
            ],
        ),
    ]
